<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.6.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTblSettingCountryTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tbl_setting_country', function (Blueprint $table) {
            $table->increments('setting_country_id');
            $table->string('setting_country_abb', 45)->charset('latin1')->collation('latin1_swedish_ci')->default('');
            $table->string('setting_country_name', 45)->charset('latin1')->collation('latin1_swedish_ci')->default('');
            $table->string('setting_country_dialcode', 10)->charset('latin1')->collation('latin1_swedish_ci');
            
            
            $table->charset = 'latin1';
            $table->collation = 'latin1_swedish_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tbl_setting_country');
    }
}
